version: '2.3'

services:
  aspnetcore:
    image: aspnetcore
    build: ./aspnetcore/
  smartkg:
    image: smartkg
    build: ./smartkg/
    ports:
      - 8082:8080
  ui:
    image: ui
    build: ./ui/
    ports:
      - 8083:8080
